#' csm_analysis
#' @description
#'
#' Once the scoreboard has been generated by `csm_mastersheet_generate`, we need to use the information
#' generated to complete statistics for each analysis, flag the statistics, and generate the scoreboard.
#'
#' `csm_analysis` is a wrapper function which calls all sub-analyses given a properly configured
#' CSMConfigMastersheet. Indeed, only required argument is a properly configured `mastersheet`,
#' literally the output of `csm_mastersheet_generate`.
#'
#' `csm_analysis` is responsible for calling the following functions
#'
#' + `analysis_aecnt`
#' + `analysis_aegap`
#' + `analysis_aei`
#' + `analysis_underdose`
#' + `analysis_vitals`
#'
#'
#' @param mastersheet All of the output from csm_mastersheet_generate
#' @param debugging Whether to enter the debugger at predictable locations
#' @param analysis_filter String vector to subset mastersheet i.e, run c('aei', 'underdose') only
#'
#'
#' @export csm_analysis
#'
#' @seealso csm_analysis_loop list_to_lower
#'
#' @family study_signal_generator
#'
#' @family csm_analysis
#'
#'
csm_analysis <- function(mastersheet = NULL,
                         debugging = FALSE,
                         analysis_filter = NULL) {
  parent_environment(function_name = "csm_analysis")

  analysis_names <- unique(mastersheet$flagging_setup$analysis)

  if (!is.null(analysis_filter)) {
    analysis_names <- analysis_names[analysis_names %in% analysis_filter]
  }

  analysis_results <- map(
    analysis_names,
    csm_analysis_loop,
    mastersheet = mastersheet,
    debugging = debugging
  )

  names(analysis_results) <- analysis_names

  analysis_results <- list_to_lower(analysis_results)

  analysis_results
}

#' csm_analysis_loop
#'
#' @description Given the name of an analysis (vitals, aegap, etc.),
#' and the mastersheet, csm_analysis_loop
#'
#' 1. Chooses the appropriate program to run for a particular analysis
#' 2. Determines the file path of the data (`pull_path`) and reads it in with `csm_data_load`
#' 3. Grabs parameters from the mastersheet with `make_configuration`
#' 4. Generates statistics and flags with `analysis_*`
#'
#' @param analysis_to_run Name of an analysis, like ae or vitals
#' @param mastersheet The full mastersheet, generated from csm_mastersheet_generate
#' @param debugging FALSE If TRUE, stops the debugger at natural locations
#' @family csm_analysis
#' @export csm_analysis_loop
csm_analysis_loop <- function(analysis_to_run, mastersheet, debugging = FALSE) {
  parent_environment("Running analysis level code...")
  csm_cli_title(paste0("BEGIN ANALYSIS ", analysis_to_run))

  analysis_result <- switch(analysis_to_run,
    # This code shows which analysis are currently hooked up, in some way.
    "aei" = tryCatch(expr = {{ input <- ANALYSIS_PREPROCESS(
      mastersheet,
      "aei",
      "compareproportion",
      debugging
    )




    parameters <- input$configuration$parameters
    walk2(
      parameters$parameter,
      parameters$value,
      ~ setenv(..1, ..2, quiet = FALSE)
    )

    on.exit({
      walk(
        parameters$parameter,
        ~ setenv(..1, "", quiet = FALSE)
      )
    })


    result <- analysis_aei(
      input$data,
      input$configuration
    ) }}, error = function(err) {
      tibble(
        error = as.character(err),
        analysis = "aei"
      )
    }),
    "retention" = tryCatch(expr = {{ input <- ANALYSIS_PREPROCESS(
      mastersheet,
      "retention",
      "compareproportion",
      debugging
    )

    parameters <- input$configuration$parameters
    walk2(
      parameters$parameter,
      parameters$value,
      ~ setenv(..1, ..2, quiet = FALSE)
    )

    on.exit({
      walk(
        parameters$parameter,
        ~ setenv(..1, "", quiet = FALSE)
      )
    })


    result <- analysis_retention(
      input$data,
      input$configuration
    ) }}, error = function(err) {
      tibble(
        error = as.character(err),
        analysis = "retention"
      )
    }),
    # aecnt -------------------------------------------------------------------
    "aecnt" = {
      tryCatch(expr = {
        input <- ANALYSIS_PREPROCESS(
          mastersheet,
          "aecnt",
          NA,
          debugging
        )
        parameters <- input$configuration$parameters
        walk2(
          parameters$parameter,
          parameters$value,
          ~ setenv(..1, ..2, quiet = FALSE)
        )

        on.exit({
          walk(
            parameters$parameter,
            ~ setenv(..1, "", quiet = FALSE)
          )
        })

        input$data <- filter(input$data, effect != "country")
        input$configuration$configuration <- distinct(input$configuration$configuration)
        analysis_aecnt(
          input$data,
          input$configuration
        )
      }, error = function(err) {
        tibble(
          error = as.character(err),
          analysis = "aecnt"
        )
      })
    },

    # vitals ------------------------------------------------------------------
    "vitals" = {
      tryCatch(expr = {
        input <- ANALYSIS_PREPROCESS(
          mastersheet,
          "vitals",
          NA,
          debugging
        )

        parameters <- input$configuration$parameters
        walk2(
          parameters$parameter,
          parameters$value,
          ~ setenv(..1, ..2, quiet = FALSE)
        )

        on.exit({
          walk(
            parameters$parameter,
            ~ setenv(..1, "", quiet = FALSE)
          )
        })
        input$data <- filter(input$data, siteid != "")
        input$data <-
          input$data %>%
          inner_join(
            mutate(input$configuration$configuration, paramcd = signals)
          )

        output <- analysis_vitals(
          input$data,
          input$configuration
        ) %>% as_tibble()

        output %>% glimpse()
      }, error = function(err) {
        tibble(
          error = as.character(err),
          analysis = "vitals"
        )
      })
    },
    # ae gap ------------------------------------------------------------------
    "aegap" = {
      tryCatch(expr = {
        input <- ANALYSIS_PREPROCESS(
          mastersheet,
          "aegap",
          c("compareproportion", "dosinganalysis", "tukeyoutliers"),
          debugging
        )

        parameters <- input$configuration$parameters
        walk2(
          parameters$parameter,
          parameters$value,
          ~ setenv(..1, ..2, quiet = FALSE)
        )

        on.exit({
          walk(
            parameters$parameter,
            ~ setenv(..1, "", quiet = FALSE)
          )
        })

        analysis_aegap(
          input$data,
          input$configuration
        )
      }, error = function(err) {
        tibble(
          error = as.character(err),
          analysis = "aegap"
        )
      })
    },
    # underdose ---------------------------------------------------------------
    "underdose" = {
      tryCatch(expr = {
        input <- ANALYSIS_PREPROCESS(
          mastersheet,
          "underdose",
          c("compareproportion", "dosinganalysis", "tukeyoutliers"),
          debugging
        )

        parameters <- input$configuration$parameters
        walk2(
          parameters$parameter,
          parameters$value,
          ~ setenv(..1, ..2, quiet = FALSE)
        )

        on.exit({
          walk(
            parameters$parameter,
            ~ setenv(..1, "", quiet = FALSE)
          )
        })

        analysis_underdose(
          input$data,
          input$configuration
        )
      }, error = function(err) {
        tibble(
          error = as.character(err),
          analysis = "underdose"
        )
      })
    },
    # diet --------------------------------------------------------------------
    "diet" = tryCatch(expr = {{ input <- ANALYSIS_PREPROCESS(
      mastersheet,
      "diet",
      "compareproportion",
      debugging
    )

    parameters <- input$configuration$parameters
    walk2(
      parameters$parameter,
      parameters$value,
      ~ setenv(..1, ..2, quiet = FALSE)
    )

    on.exit({
      walk(
        parameters$parameter,
        ~ setenv(..1, "", quiet = FALSE)
      )
    })

    result <- analysis_diet(
      input$data,
      input$configuration
    ) }}, error = function(err) {
      tibble(
        error = as.character(err),
        analysis = "diet"
      )
    }),
    # diet --------------------------------------------------------------------
    "misseddose" = tryCatch(expr = {{ input <- ANALYSIS_PREPROCESS(
      mastersheet,
      "misseddose",
      "compareproportion",
      debugging
    )

    parameters <- input$configuration$parameters
    walk2(
      parameters$parameter,
      parameters$value,
      ~ setenv(..1, ..2, quiet = FALSE)
    )

    on.exit({
      walk(
        parameters$parameter,
        ~ setenv(..1, "", quiet = FALSE)
      )
    })

    result <- analysis_miseddose(
      input$data,
      input$configuration
    ) }}, error = function(err) {
      tibble(
        error = as.character(err),
        analysis = "misseddose"
      )
    }),
    "rgv" = tryCatch(expr = {{ input <- ANALYSIS_PREPROCESS(
      mastersheet,
      "rgv",
      "compareproportion",
      debugging
    )

    parameters <- input$configuration$parameters
    walk2(
      parameters$parameter,
      parameters$value,
      ~ setenv(..1, ..2, quiet = FALSE)
    )

    on.exit({
      walk(
        parameters$parameter,
        ~ setenv(..1, "", quiet = FALSE)
      )
    })

    input_data <- transmute(input$data,
      param = paramcd, siteid,
      subject = numsubj,
      nrepgv = numrepgv,
      n = numgv,
      cutdt
    )
    result <- analysis_gv(
      input_data,
      input$configuration
    )


    left_join(rename(result, paramcd = signals), distinct(transmute(input$data, param, paramcd))) }}, error = function(err) {
      tibble(
        error = as.character(err),
        analysis = "rgv"
      )
    }),
    "rgm" = tryCatch(expr = {{ input <- ANALYSIS_PREPROCESS(
      mastersheet,
      "rgm",
      "compareproportion",
      debugging
    )

    parameters <- input$configuration$parameters
    walk2(
      parameters$parameter,
      parameters$value,
      ~ setenv(..1, ..2, quiet = FALSE)
    )

    on.exit({
      walk(
        parameters$parameter,
        ~ setenv(..1, "", quiet = FALSE)
      )
    })

    result <- analysis_gm(
      input$data,
      input$configuration
    ) }}, error = function(err) {
      tibble(
        error = as.character(err),
        analysis = "rgm"
      )
    }),
    # diet --------------------------------------------------------------------
    "gm" = tryCatch(expr = {{ input <- ANALYSIS_PREPROCESS(
      mastersheet,
      "gm",
      "compareproportion",
      debugging
    )

    parameters <- input$configuration$parameters
    walk2(
      parameters$parameter,
      parameters$value,
      ~ setenv(..1, ..2, quiet = FALSE)
    )

    on.exit({
      walk(
        parameters$parameter,
        ~ setenv(..1, "", quiet = FALSE)
      )
    })

    result <- analysis_gm(
      input$data,
      input$configuration
    ) }}, error = function(err) {
      tibble(
        error = as.character(err),
        analysis = "gm"
      )
    }),
    # <new analysis> ----------------------------------------------------------
    {
      # Default case, if nothing works in the switch above.
      stop(
        glue("\nAnalysis not yet configured, analysis_name={analysis_to_run}.")
      )
    }
  )

  analysis_result <- as_tibble(analysis_result)
  analysis_result
}

#' ANALYSIS_PREPROCESS
#' @export ANALYSIS_PREPROCESS
ANALYSIS_PREPROCESS <- function(mastersheet, analysis_name, parameters, debugging = FALSE) {
  data_path <- pull_path(mastersheet, analysis_name)
  data <- csm_data_load(data_path)
  # set this as signal and analysis
  configuration <- make_configuration(mastersheet, parameters, analysis_name)
  parameters <- configuration$parameters
  configuration$parameters <- get_parameters(parameters, analysis_name)
  list(data = data, configuration = configuration)
}


#' setenv
#' @export setenv
setenv <- function(var, value, quiet = TRUE) {
  stopifnot(is.character(var), !is.na(var), length(value) == 1L, is.atomic(value))
  qc <- as.call(c(list(quote(Sys.setenv)), setNames(list(value), var)))
  if (!quiet) print(qc)
  eval(qc)
}


#' get_parameters
#' @export get_parameters
get_parameters <- function(parameters, parameter_name) {
  default_params <-
    parameters %>%
    filter(analysis %in% c("default"))

  if (parameter_name %in% parameters$analysis) {
    analysis_parameters <-
      parameters %>%
      filter(analysis %in% c(parameter_name))

    default_params <-
      default_params %>%
      filter(!(parameter %in% analysis_parameters$parameter))

    default_params <-
      bind_rows(
        default_params,
        analysis_parameters
      )
  }
  default_params
}
